spring.application.name=dtoPractice
spring.datasource.username=postgres
spring.datasource.password=8442
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.datasource.url=jdbc:postgresql://192.168.1.114:5435/dtoPractice
spring.datasource.url=jdbc:postgresql://localhost:5435/dtoPractice